{
 "title": "Huawei UPS 2000",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "System Uptime",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_sysUpTime / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Remaining",
   "type": "gauge",
   "description": "Battery Charge Remaining Expressed as a Percent of Full Charge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_upsEstimatedChargeRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Until Battery Depletion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_upsEstimatedMinutesRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds On Battery",
   "type": "gauge",
   "description": "If the unit is on battery power, the elapsed time since the UPS last switched to battery power, or the time since the network management subsystem was last restarted, whichever is less - 1.3.6.1.2.1.33.1.2.2",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsSecondsOnBattery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsAlarmsPresent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Percent Load",
   "type": "stat",
   "description": "The percentage of the UPS power capacity presently being used on this output line, i.e., the greater of the percent load of true power capacity and the percent load of VA. - 1.3.6.1.2.1.33.1.4.4.1.5",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsOutputPercentLoad", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Current",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsBatteryCurrent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsBatteryVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_upsInputVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_upsOutputVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Bypass Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    { "expr": "ups_upsBypassFrequency / 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "ups_upsOutputCurrent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ambient temperature at or near the UPS Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ups_upsBatteryTemperature / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Bypass Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "targets": [
    { "expr": "ups_upsBypassVoltage", "legendFormat": "__auto" }
   ]
  }
 ]
}