# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "pg" {
    conn_str    = "postgres://terraform_state:WR2rnNyiLIb-gUcIxOeF@10.0.20.200:5432/terraform_state?sslmode=disable"
    schema_name = "nextcloud"
  }
}
