apiVersion: v1
data:
  Corefile: |
    .:53 {
      #log
        errors
        health {
            lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
            pods insecure
            fallthrough in-addr.arpa ip6.arpa
            ttl 30
        }
        prometheus :9153
        #forward . 1.1.1.1
        forward . 10.0.20.1
        #forward . /etc/resolv.conf
        cache {
          success 10000 300 6
          denial 10000 300 60 
        }
        loop
        reload
        loadbalance
    } 
    viktorbarzin.lan:53 {
      #log
      errors
      #forward . 10.102.184.76
      forward . 10.0.20.101:30053 # this must be the same as the technitium nodeport svc
      #forward . technitium-dns.technitium.svc.cluster.local
        cache {
          success 10000 300 6
          denial 10000 300 60 
        }
        }
kind: ConfigMap
metadata:
  name: coredns
  namespace: kube-system
