# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
data "vault_kv_secret_v2" "cf_platform" {
  mount = "secret"
  name  = "platform"
}

provider "cloudflare" {
  api_key = data.vault_kv_secret_v2.cf_platform.data["cloudflare_api_key"]
  email   = "vbarzin@gmail.com"
}
