# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  required_providers {
    # Floor, not pin: hashicorp/kubernetes 3.0.x–3.1.x ship a provider-side
    # resource-identity bug ("Missing Resource Identity After Update") that
    # failed redis/dbaas on every CI apply that touched a resource (issue
    # #68); fixed upstream in 3.2.1. Lockfiles are gitignored, so without a
    # floor any environment can resolve back into the broken range.
    kubernetes = {
      source  = "hashicorp/kubernetes"
      version = ">= 3.2.1"
    }
    vault = {
      source  = "hashicorp/vault"
      version = "~> 4.0"
    }
    cloudflare = {
      source  = "cloudflare/cloudflare"
      version = "~> 4"
    }
    authentik = {
      source = "goauthentik/authentik"
      # Floor raised from ~> 2024.10 (which resolved to 2024.12.1) on
      # 2026-09-02. That version cannot create an email stage against authentik
      # 2026.8.1 at all: it types token_expiry as a NUMBER and always sends one,
      # even when the attribute is omitted, and the server rejects it —
      #   POST /stages/email/ -> 400
      #   {"token_expiry":["30 is not in the correct format of 'hours=3;minutes=1'."]}
      # 2025.8 types it as a string.
      #
      # MEASURED before bumping, because this provider is used by four stacks
      # and two of them gate cluster access (rbac, k8s-dashboard):
      #   - authentik stack plan: 2 to add, 0 to change, 0 to destroy
      #   - schema diff 2024.12.1 -> 2025.8.1 for every type the other three
      #     stacks use (authentik_application, authentik_provider_oauth2, and
      #     the three data sources): no newly-required attribute, no type
      #     change, no removal.
      # Note authentik_provider_oauth2 does drop `redirect_uris` in 2025.8, but
      # nothing here uses it — all four stacks already use
      # allowed_redirect_uris, which 2024.12.1 also has.
      version = "~> 2025.8"
    }
    # kubectl (gavinbunney) — workaround for hashicorp/kubernetes
    # `kubernetes_manifest` panics on Kyverno CRDs. See beads code-e2dp.
    # Declared for all stacks but only used where opted-in.
    kubectl = {
      source  = "gavinbunney/kubectl"
      version = "~> 1.14"
    }
    proxmox = {
      source  = "telmate/proxmox"
      version = "3.0.2-rc07"
    }
  }
}

variable "kube_config_path" {
  type    = string
  default = "~/.kube/config"
}

provider "kubernetes" {
  config_path = var.kube_config_path
}

provider "helm" {
  kubernetes = {
    config_path = var.kube_config_path
  }
}

provider "vault" {
  address          = "https://vault.viktorbarzin.me"
  skip_child_token = true
}

provider "kubectl" {
  config_path      = var.kube_config_path
  load_config_file = true
}
