/**
 * outage-failover — friendly error page when the homelab origin is dead (ADR-0020).
 * Deployed by Terraform (worker.tf, same directory); runs on every proxied
 * hostname of viktorbarzin.me via two zone routes.
 *
 * Interception condition — exactly {fetch threw, 530, 521, 522, 523}:
 *   530 (1033 in the body) = cloudflared tunnel down/unregistered
 *   521 / 522 / 523        = edge could not connect/reach the origin
 * These four are generated by Cloudflare itself when the origin is
 * unreachable — no app behind Traefik can ever emit them, so intercepting
 * them can never mask an application error.
 *
 * 502/504 are deliberately NOT intercepted: with the cluster up they come
 * from apps or the in-cluster error-pages middleware, which owns them. A 502
 * can also come from cloudflared while Traefik alone is down, but that narrow
 * slice is accepted — intercepting 502 would mask real app errors.
 *
 * Only top-level browsable requests (GET/HEAD + Accept contains text/html +
 * no websocket upgrade) get the failover page. Everything else — APIs, asset
 * fetches from JS, websockets, POSTs — returns the raw origin failure:
 * machine clients must see real errors, not a 503 HTML page.
 */

const INTERCEPT_STATUS = new Set([530, 521, 522, 523]);

// Last resort when mx2 is unreachable too (VM down / TLS not yet issued).
// Fully self-contained: no external assets, must render from this string alone.
const INLINE_FALLBACK_HTML = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>viktorbarzin.me — temporarily unavailable</title>
<style>
body{margin:0;min-height:100vh;display:flex;align-items:center;justify-content:center;
font-family:system-ui,-apple-system,sans-serif;background:#14161a;color:#e8e8e8}
main{max-width:34rem;padding:2rem;text-align:center}
h1{font-size:1.4rem;margin-bottom:.5rem}
p{color:#b5bac1;line-height:1.5}
a{color:#8ab4f8}
</style>
</head>
<body>
<main>
<h1>Sorry — this service is temporarily unreachable</h1>
<p>The server behind viktorbarzin.me is not responding right now.
It is usually back within a few minutes.</p>
<p>Live status: <a href="https://status.viktorbarzin.me">status.viktorbarzin.me</a></p>
</main>
</body>
</html>
`;

function isBrowsable(request) {
  const accept = request.headers.get("Accept") || "";
  const upgrade = request.headers.get("Upgrade") || "";
  return (
    (request.method === "GET" || request.method === "HEAD") &&
    accept.includes("text/html") &&
    !upgrade.toLowerCase().includes("websocket")
  );
}

function failoverHeaders(source) {
  return {
    "content-type": "text/html; charset=utf-8",
    "retry-after": "120",
    "cache-control": "no-store",
    "x-failover": source,
  };
}

export default {
  async fetch(request) {
    let response = null;
    try {
      response = await fetch(request);
      if (!INTERCEPT_STATUS.has(response.status)) {
        // Healthy, or an app-level error (500/502/504/…): pass through untouched.
        return response;
      }
    } catch (err) {
      // fetch itself threw — same origin-unreachable class; fall through.
    }

    if (!isBrowsable(request)) {
      // Machine clients get the raw origin failure. If fetch threw there is
      // nothing to forward, so synthesize the matching origin-unreachable status.
      return response !== null
        ? response
        : new Response("origin unreachable", {
            status: 530,
            headers: { "cache-control": "no-store", "x-failover": "none" },
          });
    }

    // Preferred page: /error.html served by gatus's nginx on mx2. status is
    // grey-cloud, so this fetch goes straight to mx2 — no Worker recursion.
    // Edge-cached 60s so an outage traffic spike costs ~1 subrequest/min.
    try {
      const errorPage = await fetch("https://status.viktorbarzin.me/error.html", {
        cf: { cacheTtl: 60, cacheEverything: true },
      });
      if (errorPage.ok) {
        return new Response(errorPage.body, {
          status: 503,
          headers: failoverHeaders("mx2"),
        });
      }
    } catch (err) {
      // mx2 also down — fall through to the baked-in page.
    }

    return new Response(INLINE_FALLBACK_HTML, {
      status: 503,
      headers: failoverHeaders("inline"),
    });
  },
};
