/**
 * outage-failover — friendly error page when the homelab origin is dead (ADR-0020).
 * Deployed by Terraform (worker.tf, same directory).
 *
 * Interception condition — exactly {fetch threw, 530, 521, 522, 523}:
 *   530 (1033 in the body) = cloudflared tunnel down/unregistered
 *   521 / 522 / 523        = edge could not connect/reach the origin
 * These four are generated by Cloudflare itself when the origin is
 * unreachable — no app behind Traefik can ever emit them, so intercepting
 * them can never mask an application error.
 *
 * 502/504 are deliberately NOT intercepted: with the cluster up they come
 * from apps or the in-cluster error-pages middleware, which owns them.
 *
 * Only top-level browsable requests (GET/HEAD + Accept contains text/html +
 * no websocket upgrade) get the failover page. Everything else — APIs, asset
 * fetches, websockets, POSTs, non-HTML clients — passes through untouched.
 *
 * ROUTING (worker.tf): wildcard *.viktorbarzin.me/* + apex, MINUS "no-worker"
 * carve-out routes for the quota hogs / non-browsable hosts (terminal, matrix,
 * vault, t3, xray-*, …) — Cloudflare bills a Worker invocation on ROUTE MATCH,
 * so those high-volume hosts are excluded to stay under the free 100k/day quota.
 *
 * HISTORY: the retired rybbit-analytics injection was briefly folded in here
 * (2026-07-17) then removed the same day — the Rybbit instance is unconfigured
 * (0 sites, analytics dead since ~2026-04-13), so the injection did nothing.
 * This Worker is pure outage-failover; re-add injection only if Rybbit is set up.
 */

const INTERCEPT_STATUS = new Set([530, 521, 522, 523]);

// The primary outage page, injected at deploy time by worker.tf from
// error_page.html (same content mx2's nginx serves at /error.html — keep the
// two in sync when editing). Fully self-contained: inline CSS, no external
// assets; live per-service status loads CLIENT-side from the gatus API on
// status.viktorbarzin.me (grey-cloud, so the visitor's browser reaches mx2
// directly even mid-outage; CORS is enabled on /api/). Baking it in — rather
// than subrequesting mx2 — matters because Worker fetch() to a same-zone
// grey-cloud hostname was observed failing on 2026-07-08 (the mx2 fetch below
// remains as an opportunistic first try; this constant is the reliable path).
const INLINE_FALLBACK_HTML = "__INLINE_PAGE_JSON__";

function isBrowsable(request) {
  const accept = request.headers.get("Accept") || "";
  const upgrade = request.headers.get("Upgrade") || "";
  return (
    (request.method === "GET" || request.method === "HEAD") &&
    accept.includes("text/html") &&
    !upgrade.toLowerCase().includes("websocket")
  );
}

function failoverHeaders(source) {
  return {
    "content-type": "text/html; charset=utf-8",
    "retry-after": "120",
    "cache-control": "no-store",
    "x-failover": source,
  };
}

export default {
  async fetch(request) {
    let response = null;
    try {
      response = await fetch(request);
      if (!INTERCEPT_STATUS.has(response.status)) {
        // Healthy, or an app-level error (500/502/504/…): pass through untouched.
        return response;
      }
    } catch (err) {
      // fetch itself threw — same origin-unreachable class; fall through.
    }

    if (!isBrowsable(request)) {
      // Machine clients get the raw origin failure. If fetch threw there is
      // nothing to forward, so synthesize the matching origin-unreachable status.
      return response !== null
        ? response
        : new Response("origin unreachable", {
            status: 530,
            headers: { "cache-control": "no-store", "x-failover": "none" },
          });
    }

    // Preferred page: /error.html served by gatus's nginx on mx2. status is
    // grey-cloud, so this fetch goes straight to mx2 — no Worker recursion.
    // Edge-cached 60s so an outage traffic spike costs ~1 subrequest/min.
    try {
      const errorPage = await fetch("https://status.viktorbarzin.me/error.html", {
        cf: { cacheTtl: 60, cacheEverything: true },
      });
      if (errorPage.ok) {
        return new Response(errorPage.body, {
          status: 503,
          headers: failoverHeaders("mx2"),
        });
      }
    } catch (err) {
      // mx2 also down — fall through to the baked-in page.
    }

    return new Response(INLINE_FALLBACK_HTML, {
      status: 503,
      headers: failoverHeaders("inline"),
    });
  },
};
