/**
 * outage-failover — one Cloudflare Worker that does BOTH jobs on viktorbarzin.me
 * (ADR-0020; rybbit-analytics consolidated in 2026-07-17). Deployed by Terraform
 * (worker.tf, same directory).
 *
 *   1. OUTAGE PAGE — when the origin is unreachable (fetch threw / 530 / 521 /
 *      522 / 523) AND the request is browsable (GET/HEAD + Accept: text/html +
 *      non-WebSocket): serve the friendly outage page. Everything else (APIs,
 *      asset fetches, websockets, POSTs, non-HTML clients) gets the raw origin
 *      failure — machine clients must see real errors.
 *        530 (1033 in body) = cloudflared tunnel down/unregistered
 *        521 / 522 / 523     = edge could not connect/reach the origin
 *      These four are generated by Cloudflare itself when the origin is down — no
 *      app behind Traefik can emit them, so intercepting them never masks an app
 *      error. 502/504 are deliberately NOT intercepted (apps / the in-cluster
 *      error-pages middleware own them).
 *
 *   2. ANALYTICS — on a healthy text/html response whose host is in SITE_IDS,
 *      inject the Rybbit tracking <script> before </head> via HTMLRewriter. This
 *      folds in the retired out-of-band rybbit-analytics Worker.
 *
 *   3. Everything else passes through UNTOUCHED.
 *
 * ROUTING (worker.tf): this Worker runs on the *.viktorbarzin.me/* wildcard + the
 * apex, MINUS "no-worker" carve-out routes for the quota hogs / non-browsable
 * hosts (terminal, terminal-ro, matrix, vault, t3, t3-afk, xray-grpc, xray-ws,
 * and rybbit itself — self-amplification). Rationale: Cloudflare bills a Worker
 * invocation on ROUTE MATCH before this code runs, so wildcard-matching those
 * high-volume hosts (terminal alone was ~55% of zone traffic) drove the free-tier
 * 100k/day quota to 94.5% on 2026-07-16. Carving them out drops usage to ~30k/day
 * while every browsable host keeps outage coverage.
 *
 * INVARIANTS (do not break):
 *  - Guard content-type BEFORE HTMLRewriter: a WebSocket 101 upgrade has no
 *    text/html content-type, so it returns the original response with its
 *    `webSocket` intact (nextcloud notify_push etc. are covered WS hosts).
 *  - HTMLRewriter NEVER runs on the outage branch (never inject into the 503 page
 *    or a raw error body).
 *  - DEFAULT_SITE_ID stays null: browsable hosts NOT tracked by Rybbit still get
 *    outage coverage but must not emit <script data-site-id="null">.
 *  - rybbit.viktorbarzin.me is carved out in worker.tf (self-amplification: it
 *    serves the tracker JS + event POSTs).
 */

// hostname -> Rybbit site ID. Carried over verbatim from the retired
// rybbit-analytics Worker to preserve analytics behaviour exactly.
// NOTE: six keys are STALE hostnames with no live ingress (actualbudget ->
// budget-viktor/budget-anca, crowdsec -> crowdsec-web, cyberchef -> cc,
// paperless-ngx -> paperless-ai, privatebin -> pb, uptime-kuma -> uptime); they
// inject on nothing today and are kept only to avoid changing analytics in this
// consolidation. Remapping them to the real hosts (needs the matching Rybbit
// dashboard site config) is a tracked follow-up, not done here.
const SITE_IDS = {
  "viktorbarzin.me": "da853a2438d0",
  "www.viktorbarzin.me": "da853a2438d0",
  "actualbudget.viktorbarzin.me": "3e6b6b68088a", // STALE host (real: budget-viktor/budget-anca)
  "crowdsec.viktorbarzin.me": "d09137795ccc", // STALE host (real: crowdsec-web)
  "cyberchef.viktorbarzin.me": "7c460afc68c4", // STALE host (real: cc)
  "dawarich.viktorbarzin.me": "0abfd409f2fb",
  "pma.viktorbarzin.me": "942c76b8bd4d",
  "pgadmin.viktorbarzin.me": "7cef78e30485",
  "audiobookshelf.viktorbarzin.me": "17a5c7fbb077",
  "calibre.viktorbarzin.me": "ce5f8aed6bbb",
  "stacks.viktorbarzin.me": "b38fda4285df",
  "f1.viktorbarzin.me": "7e69786f66d5",
  "frigate.viktorbarzin.me": "0d4044069ff5",
  "immich.viktorbarzin.me": "35eedb7a3d2b",
  "mail.viktorbarzin.me": "082f164faa7d",
  "navidrome.viktorbarzin.me": "8a3844ff75ba",
  "networking-toolbox.viktorbarzin.me": "50e38577e41c",
  "nextcloud.viktorbarzin.me": "5a3bfe59a3fe",
  "paperless-ngx.viktorbarzin.me": "be6d140cbed8", // STALE host (real: paperless-ai)
  "privatebin.viktorbarzin.me": "3ae810b0476d", // STALE host (real: pb)
  "wrongmove.viktorbarzin.me": "edee05de453d",
  "rybbit.viktorbarzin.me": "3c476801a777", // carved out in worker.tf (self-amplification); never runs
  "send.viktorbarzin.me": "c1b8f8aa831b",
  "stirling-pdf.viktorbarzin.me": "a55ac54ec749",
  "uptime-kuma.viktorbarzin.me": "8fef77b1f7fe", // STALE host (real: uptime)
  "vaultwarden.viktorbarzin.me": "b8fc85e18683",
};
const DEFAULT_SITE_ID = null;

const INTERCEPT_STATUS = new Set([530, 521, 522, 523]);

// The outage page, injected at deploy time by worker.tf from error_page.html
// (same content mx2's nginx serves at /error.html — keep the two in sync). Fully
// self-contained: inline CSS, no external assets; live per-service status loads
// CLIENT-side from the gatus API on status.viktorbarzin.me (grey-cloud, so the
// visitor's browser reaches mx2 directly even mid-outage; CORS on /api/). Baked
// in because a Worker fetch() to a same-zone grey-cloud host was observed failing
// on 2026-07-08 (the opportunistic mx2 fetch below is the first try; this is the
// reliable path).
const INLINE_FALLBACK_HTML = "__INLINE_PAGE_JSON__";

class HeadInjector {
  constructor(siteId) {
    this.siteId = siteId;
  }
  element(element) {
    element.prepend(
      `<script src="https://rybbit.viktorbarzin.me/api/script.js" data-site-id="${this.siteId}" defer></script>`,
      { html: true }
    );
  }
}

function isBrowsable(request) {
  const accept = request.headers.get("Accept") || "";
  const upgrade = request.headers.get("Upgrade") || "";
  return (
    (request.method === "GET" || request.method === "HEAD") &&
    accept.includes("text/html") &&
    !upgrade.toLowerCase().includes("websocket")
  );
}

function failoverHeaders(source) {
  return {
    "content-type": "text/html; charset=utf-8",
    "retry-after": "120",
    "cache-control": "no-store",
    "x-failover": source,
  };
}

export default {
  async fetch(request) {
    const hostname = new URL(request.url).hostname;
    let response = null;
    try {
      response = await fetch(request);
      if (!INTERCEPT_STATUS.has(response.status)) {
        // Healthy, or an app-level error (500/502/504/…). Inject analytics into
        // HTML for tracked hosts; pass everything else (websockets — no text/html
        // content-type — non-HTML, APIs, untracked hosts) through UNTOUCHED.
        const siteId = SITE_IDS[hostname] || DEFAULT_SITE_ID;
        const contentType = response.headers.get("content-type") || "";
        if (siteId && contentType.includes("text/html")) {
          return new HTMLRewriter()
            .on("head", new HeadInjector(siteId))
            .transform(response);
        }
        return response;
      }
    } catch (err) {
      // fetch itself threw — same origin-unreachable class; fall through.
    }

    // Origin unreachable (530 / 521-523 or fetch threw).
    if (!isBrowsable(request)) {
      // Machine clients get the raw origin failure. If fetch threw there is
      // nothing to forward, so synthesize the matching origin-unreachable status.
      return response !== null
        ? response
        : new Response("origin unreachable", {
            status: 530,
            headers: { "cache-control": "no-store", "x-failover": "none" },
          });
    }

    // Preferred page: /error.html served by gatus's nginx on mx2. status is
    // grey-cloud, so this fetch goes straight to mx2 — no Worker recursion.
    // Edge-cached 60s so an outage traffic spike costs ~1 subrequest/min.
    try {
      const errorPage = await fetch("https://status.viktorbarzin.me/error.html", {
        cf: { cacheTtl: 60, cacheEverything: true },
      });
      if (errorPage.ok) {
        return new Response(errorPage.body, {
          status: 503,
          headers: failoverHeaders("mx2"),
        });
      }
    } catch (err) {
      // mx2 also down — fall through to the baked-in page.
    }

    return new Response(INLINE_FALLBACK_HTML, {
      status: 503,
      headers: failoverHeaders("inline"),
    });
  },
};
