mqtt:
  enabled: false
birdseye:
  quality: 25
detect:
  fps: 1
  enabled: true
go2rtc:
  streams:
    vermont-1:
      - rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/101/3
cameras:
    # # Temp disabled until valchedrym is back up
    valchedrym-cam-1:
        enabled: true
        ffmpeg:
            inputs:
                #- path: rtsp://admin:REDACTED_RTSP_PW@192.168.0.11:554/Streaming/Channels/101 # <----- The stream you want to use for detection
                - path: rtsp://admin:REDACTED_RTSP_PW@valchedrym.ddns.net:554/Streaming/Channels/101 # <----- The stream you want to use for detection
        detect:
            enabled: false # <---- disable detection until you have a working camera feed
            width: 704 # <---- update for your camera's resolution
            height: 576 # <---- update for your camera's resolution
        rtmp:
          enabled: false
        record:
          enabled: false
        snapshots:
          enabled: false
        objects:
          # Optional: list of objects to track from labelmap.txt (full list - https://docs.frigate.video/configuration/objects)
          track:
            - person
            - bicycle
            - car
            - bird
            - cat
            - dog
            - horse
    valchedrym-cam-2:
        enabled: true
        ffmpeg:
            inputs:
                #- path: rtsp://admin:REDACTED_RTSP_PW@192.168.0.11:554/Streaming/Channels/201 # <----- The stream you want to use for detection
                - path: rtsp://admin:REDACTED_RTSP_PW@valchedrym.ddns.net:554/Streaming/Channels/201 # <----- The stream you want to use for detection
        detect:
            enabled: false # <---- disable detection until you have a working camera feed
            width: 704 # <---- update for your camera's resolution
            height: 576 # <---- update for your camera's resolution
        rtmp:
          enabled: false
        record:
          enabled: false
        snapshots:
          enabled: false
        objects:
          # Optional: list of objects to track from labelmap.txt (full list - https://docs.frigate.video/configuration/objects)
          track:
            - person
            - bicycle
            - car
            - bird
            - cat
            - dog
            - horse
    vermont-1:
      enabled: true
      ffmpeg:
        inputs:
          - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/101/3       # <----- The stream you want to use for detection
            roles:
              - record
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
      detect:
        enabled: false
    vermont-2:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/201/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-3:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/301/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-4:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/401/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-5:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/501/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-6:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/601/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-7:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/701/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-8:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/801/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    vermont-9:
      enabled: true
      ffmpeg:
          inputs:
              - path: rtsp://admin:REDACTED_RTSP_PW@192.168.1.10:554/Streaming/Channels/901/1 # <----- The stream you want to use for detection
      detect:
          enabled: false # <---- disable detection until you have a working camera feed
          width: 704 # <---- update for your camera's resolution
          height: 576 # <---- update for your camera's resolution
      rtmp:
        enabled: false
      record:
        enabled: false
      snapshots:
        enabled: false
    # london-ipcam:
    #     enabled: false
    #     ffmpeg:
    #         inputs:
    #             - path: rtsp://192.168.2.2:8554/london_cam # <----- The stream you want to use for detection
    #               roles:
    #                 - rtmp
    #                 - record
    #                 - detect
    #     detect:
    #         enabled: False
    #         width: 1280
    #         height: 720
    #     record:
    #         enabled: False # Not needed for this camera but keeping for reference
    #         events:
    #           retain:
    #             default: 10
    #     objects:
    #       # Optional: list of objects to track from labelmap.txt (full list - https://docs.frigate.video/configuration/objects)
    #       track:
    #         - person
    #         - shoe
    #         - handbag
    #         - wine glass
    #         - knife
    #         - pizza
    #         - laptop
    #         - book
