authentik:
  log_level: warning
  # log_level: trace
  secret_key: ""
  existingSecret:
    secretName: "goauthentik"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: false
  postgresql:
    # host: postgresql.dbaas
    host: pgbouncer.authentik
    port: 6432
    user: authentik
    password: ""

server:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 1.5Gi
    limits:
      memory: 1.5Gi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: server
  ingress:
    enabled: false
    # hosts:
    #   - authentik.viktorbarzin.me
  podAnnotations:
    diun.enable: true
    diun.include_tags: "^202[0-9].[0-9]+.*$" # no need to annotate the worker as it uses the same image
  pdb:
    enabled: true
    minAvailable: 1
global:
  addPrometheusAnnotations: true

worker:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 1.5Gi
    limits:
      memory: 1.5Gi
  topologySpreadConstraints:
    - maxSkew: 1
      topologyKey: kubernetes.io/hostname
      whenUnsatisfiable: ScheduleAnyway
      labelSelector:
        matchLabels:
          app.kubernetes.io/component: worker
  pdb:
    enabled: true
    maxUnavailable: 1

postgresql:
  enabled: false
