authentik:
  log_level: warning
  secret_key: "${secret_key}"
  # This sends anonymous usage-data, stack traces on errors and
  # performance data to authentik.error-reporting.a7k.io, and is fully opt-in
  error_reporting:
    enabled: true
  postgresql:
    host: postgresql.dbaas
    user: authentik
    password: ${postgres_password}
  redis:
    host: redis.redis

server:
  replicas: 3
  ingress:
    enabled: false
    # hosts:
    #   - authentik.viktorbarzin.me
  podAnnotations:
    diun.enable: true
    diun.include_tags: "^202[0-9].[0-9]+.*$" # no need to annotate the worker as it uses the same image
global:
  addPrometheusAnnotations: true

worker:
  replicas: 3
