#!/usr/bin/env python3
"""Reconcile every running workload against what Terraform declares.

Answers "do we have stray pods". Nothing else in the stack can: Kyverno
admission decides whether a pod is ALLOWED (trusted registry, not privileged,
no host namespaces, no CAP_SYS_ADMIN) and says nothing about whether anyone
declared it. A traffic view shows what talks; a workload nobody declared and
nobody talks to is invisible there. The only source of truth for "declared" is
Terraform state, and the only way to find the difference is to subtract.

Where the declared set comes from
  Tier-1 stacks keep state in the `terraform_state` database on the CNPG
  cluster (root terragrunt.hcl: `backend = "pg"`, one schema per stack). The
  init container projects it with stray_workload_extract.sql and drops the
  result in DECLARED_FILE. 328 declarations, 1.3s, measured 2026-09-01.

  Tier-0 stacks (infra, platform, cnpg, vault, dbaas, external-secrets) keep
  LOCAL state in the repo, so a CronJob cannot read them. Their 11 workloads
  are committed as declared_tier0.json, regenerated by
  scripts/gen-tier0-workload-inventory.py. A stale file there produces a
  visible FALSE POSITIVE (a newly declared tier-0 workload reads as stray), not
  a false negative, and the alert text says which file to regenerate.

What counts as accounted for, and why each rule exists
  exempt          an explicit entry in exempt.json, one reason per line.
                  Today: kubeadm's coredns and kube-proxy, which the control
                  plane owns and Terraform deliberately does not.
  terraform       kind/namespace/name appears in the declared set. 311 of 383
                  workloads, measured 2026-09-01.
  helm            the workload carries meta.helm.sh/release-name and that
                  release is a declared helm_release. A chart's Deployments are
                  not in Terraform state — the RELEASE is — so without this
                  rule every chart-shipped workload reads as stray. 50 today.
                  A Helm-owned workload whose release is NOT declared is a
                  finding: that is a hand-run `helm install`.
  owned           the object has an ownerReference, so a Kubernetes controller
                  made it: CronJob -> Job -> Pod, Deployment -> ReplicaSet ->
                  Pod, operator CR -> Deployment. The controller itself is
                  reconciled by this same job, so trusting the chain does not
                  create a blind spot. ~460-471 objects today, almost all
                  pods, so the number moves between runs.
  reconciler      app.kubernetes.io/managed-by names an in-cluster reconciler
                  listed in exempt.json. Authentik's server creates its outpost
                  Deployments this way and sets no ownerReference, so they look
                  bare. 2 today.
  too-new         a bare Pod younger than POD_GRACE_HOURS. A debug pod someone
                  is actively using is not debris.
  dynamic-pod     a bare Pod matching a label in exempt.json's pod_labels. The
                  proxy stack starts per-user browser pods with no owner; they
                  are declared as behaviour, not as objects.

Refusing to cry wolf
  The failure that matters is not missing a stray workload, it is reporting 383
  of them because the inventory came back short. helm-unstick spent an unknown
  stretch reporting success while inspecting nothing, because an OOM-killed
  kubectl returned an empty list into a `|| true`. Two guards here, and both
  push `stray_workload_inventory_ok 0` and exit non-zero rather than reporting:

    - fewer than MIN_DECLARED declarations (339 today, floor 150)
    - findings exceeding MAX_FINDING_RATIO of the live set (0.3% today)

  The SQL runs under ON_ERROR_STOP=1 for the same reason: a schema the reader
  role cannot SELECT aborts the extraction instead of shortening it.

Pure stdlib on purpose (no pip/apk at runtime — see the status-page-pusher
anti-pattern in .claude/CLAUDE.md).
"""

import json
import os
import ssl
import sys
import urllib.request
from datetime import datetime, timedelta, timezone

# A bare Pod younger than this is somebody's live debug session, not debris.
POD_GRACE_HOURS = 24

# Guards against reporting a broken inventory as a cluster full of strays.
# Measured 2026-09-01: 339 declarations (328 Tier-1 + 11 Tier-0), 383
# workloads, 453 pods, 1 finding. The floor is ~2.2x below today's count, so
# ordinary stack removals never trip it and a structural failure always does.
MIN_DECLARED = 150
MAX_FINDING_RATIO = 0.25

SA = "/var/run/secrets/kubernetes.io/serviceaccount"

# Metadata-only listing. The pod specs are the bulk of the payload and this job
# reads none of them, so ask the apiserver to project them away rather than
# parsing 450 pod specs to look at their ownerReferences.
PARTIAL_METADATA = "application/json;as=PartialObjectMetadataList;g=meta.k8s.io;v=v1"

RESOURCES = [
    ("Deployment", "/apis/apps/v1/deployments"),
    ("StatefulSet", "/apis/apps/v1/statefulsets"),
    ("DaemonSet", "/apis/apps/v1/daemonsets"),
    ("CronJob", "/apis/batch/v1/cronjobs"),
    ("Pod", "/api/v1/pods"),
]

HELM_RELEASE_NAME = "meta.helm.sh/release-name"
HELM_RELEASE_NAMESPACE = "meta.helm.sh/release-namespace"
MANAGED_BY = "app.kubernetes.io/managed-by"


def _parse(ts):
    return datetime.strptime(ts, "%Y-%m-%dT%H:%M:%SZ").replace(tzinfo=timezone.utc)


def parse_declared(text):
    """Parse the extractor's `kind|namespace|name|stack` lines.

    Returns (workloads, releases) where workloads maps (kind, namespace, name)
    to the declaring stack and releases maps (namespace, release) to the same.
    """
    workloads, releases = {}, {}
    for lineno, raw in enumerate(text.splitlines(), 1):
        line = raw.strip()
        if not line:
            continue
        parts = line.split("|")
        if len(parts) != 4:
            raise ValueError(f"declared line {lineno} has {len(parts)} fields, want 4: {line!r}")
        kind, namespace, name, stack = parts
        if not kind or not name:
            raise ValueError(f"declared line {lineno} is missing kind or name: {line!r}")
        if kind == "HelmRelease":
            releases[(namespace, name)] = stack
        else:
            workloads[(kind, namespace, name)] = stack
    return workloads, releases


def classify(item, declared, releases, exempt, now,
             pod_grace_hours=POD_GRACE_HOURS):
    """Return (accounted_reason, finding_reason) for one live object.

    Exactly one of the two is non-None. `finding_reason` non-None means the
    object is unaccounted for and belongs in the report.
    """
    kind, ns, name = item["kind"], item["namespace"], item["name"]
    labels = item.get("labels") or {}
    anns = item.get("annotations") or {}
    key = (kind, ns, name)

    # Explicit exemptions win over everything, so a documented decision is
    # never re-litigated by a later rule.
    if key in exempt["workloads"]:
        return "exempt:" + exempt["workloads"][key], None

    if key in declared:
        return "terraform:" + declared[key], None

    release = anns.get(HELM_RELEASE_NAME)
    release_ns = anns.get(HELM_RELEASE_NAMESPACE) or ns
    if release and (release_ns, release) in releases:
        return "helm:" + releases[(release_ns, release)], None

    # An ownerReference before a managed-by label, deliberately: the
    # ownerReference is maintained by the apiserver, while managed-by is a
    # label anything can write. Preferring the stronger evidence also keeps the
    # exemption list as small as possible, and it means a chart-shipped CR whose
    # operator creates a workload is accounted for by that chain rather than by
    # the inherited release annotation below.
    if item.get("owner_kind"):
        return "owned-by:" + item["owner_kind"], None

    managed_by = labels.get(MANAGED_BY)
    if managed_by and managed_by in exempt["managed_by"]:
        return "reconciler:" + managed_by, None

    if release:
        return None, f"helm-release-undeclared:{release_ns}/{release}"

    if kind == "Pod":
        for lbl, value in exempt["pod_labels"]:
            if labels.get(lbl) == value:
                return f"dynamic-pod:{lbl}={value}", None
        age = _parse(now) - _parse(item["created"])
        if age < timedelta(hours=pod_grace_hours):
            return "too-new", None
        return None, "orphan-pod"

    return None, "undeclared"


def reconcile(live, declared, releases, exempt, now,
              pod_grace_hours=POD_GRACE_HOURS,
              min_declared=MIN_DECLARED,
              max_finding_ratio=MAX_FINDING_RATIO):
    """Subtract the declared set from the live set.

    Returns (findings, accounted, refusal). `refusal` is None on a usable run
    and otherwise a sentence naming why the result was thrown away; when it is
    set, `findings` is empty on purpose — a broken inventory must not read as a
    cluster full of stray workloads.
    """
    total_declared = len(declared) + len(releases)
    if total_declared < min_declared:
        return [], {}, (
            f"declared inventory holds {total_declared} entries, below the floor of "
            f"{min_declared} — treating this as a broken extraction, not an empty cluster"
        )

    findings, accounted = [], {}
    for item in live:
        reason, finding = classify(item, declared, releases, exempt, now,
                                   pod_grace_hours=pod_grace_hours)
        if finding is None:
            accounted[reason.split(":")[0]] = accounted.get(reason.split(":")[0], 0) + 1
            continue
        findings.append({
            "kind": item["kind"],
            "namespace": item["namespace"],
            "name": item["name"],
            "reason": finding,
        })

    if live and len(findings) > max_finding_ratio * len(live):
        return [], accounted, (
            f"{len(findings)} of {len(live)} live objects look unaccounted for "
            f"(> {max_finding_ratio:.0%}) — that is an inventory fault, not a cluster fault"
        )

    findings.sort(key=lambda f: (f["kind"], f["namespace"], f["name"]))
    return findings, accounted, None


def _api(path, accept=None):
    token = open(f"{SA}/token").read().strip()
    host = os.environ["KUBERNETES_SERVICE_HOST"]
    port = os.environ.get("KUBERNETES_SERVICE_PORT", "443")
    ctx = ssl.create_default_context(cafile=f"{SA}/ca.crt")
    headers = {"Authorization": f"Bearer {token}"}
    if accept:
        headers["Accept"] = accept
    req = urllib.request.Request(f"https://{host}:{port}{path}", headers=headers)
    with urllib.request.urlopen(req, context=ctx, timeout=120) as resp:
        return json.load(resp)


def _list_all(path, accept, page=500):
    """Follow the apiserver's continue tokens.

    A truncated live list silently HIDES stray workloads, so paginate rather
    than passing a large `limit` and hoping it covers the cluster.
    """
    token, out = "", []
    while True:
        sep = "&" if "?" in path else "?"
        url = f"{path}{sep}limit={page}" + (f"&continue={token}" if token else "")
        data = _api(url, accept=accept)
        out.extend(data.get("items", []))
        token = (data.get("metadata") or {}).get("continue") or ""
        if not token:
            return out


def collect(resources=RESOURCES):
    """Flatten every live workload and pod into the reconciler's shape."""
    live = []
    for kind, path in resources:
        for obj in _list_all(path, PARTIAL_METADATA):
            m = obj["metadata"]
            owners = m.get("ownerReferences") or []
            live.append({
                "kind": kind,
                "namespace": m.get("namespace", ""),
                "name": m["name"],
                "labels": m.get("labels") or {},
                "annotations": m.get("annotations") or {},
                "owner_kind": owners[0]["kind"] if owners else None,
                "created": m["creationTimestamp"],
            })
    return live


def load_exempt(path):
    """Read exempt.json into the shape classify() wants."""
    raw = json.load(open(path))
    return {
        "workloads": {
            (e["kind"], e["namespace"], e["name"]): e["reason"]
            for e in raw.get("workloads", [])
        },
        "pod_labels": [(e["label"], e["value"]) for e in raw.get("pod_labels", [])],
        "managed_by": {e["value"] for e in raw.get("managed_by", [])},
    }


def load_declared(declared_file, tier0_file):
    """Merge the Tier-1 projection with the committed Tier-0 inventory."""
    workloads, releases = parse_declared(open(declared_file).read())
    tier0 = json.load(open(tier0_file))
    for kind, namespace, name, stack in tier0.get("declarations", []):
        if kind == "HelmRelease":
            releases[(namespace, name)] = stack
        else:
            workloads[(kind, namespace, name)] = stack
    return workloads, releases


def push(findings, accounted, refusal, declared_total, live_total, pushgateway):
    ok = 0 if refusal else 1
    lines = [
        "# HELP stray_workload A running workload or pod that no Terraform declaration accounts for.",
        "# TYPE stray_workload gauge",
    ]
    for f in findings:
        lines.append(
            'stray_workload{kind="%s",namespace="%s",name="%s",reason="%s"} 1'
            % (f["kind"], f["namespace"], f["name"], f["reason"])
        )
    lines += [
        "# HELP stray_workload_count Number of running workloads and pods no declaration accounts for.",
        "# TYPE stray_workload_count gauge",
        "stray_workload_count %d" % len(findings),
        "# HELP stray_workload_declared_total Declarations read out of Terraform state plus the Tier-0 inventory.",
        "# TYPE stray_workload_declared_total gauge",
        "stray_workload_declared_total %d" % declared_total,
        "# HELP stray_workload_live_total Live workloads and pods examined.",
        "# TYPE stray_workload_live_total gauge",
        "stray_workload_live_total %d" % live_total,
        "# HELP stray_workload_inventory_ok 1 when the declared inventory was usable, 0 when the run refused to report.",
        "# TYPE stray_workload_inventory_ok gauge",
        "stray_workload_inventory_ok %d" % ok,
        "# HELP stray_workload_last_run_timestamp Unix time of the last reconciler run.",
        "# TYPE stray_workload_last_run_timestamp gauge",
        "stray_workload_last_run_timestamp %d" % int(datetime.now(timezone.utc).timestamp()),
    ]
    body = ("\n".join(lines) + "\n").encode()
    req = urllib.request.Request(
        f"{pushgateway}/metrics/job/stray-workload-detect", data=body, method="PUT"
    )
    with urllib.request.urlopen(req, timeout=30) as resp:
        return resp.status


def main():
    pushgateway = os.environ.get(
        "PUSHGATEWAY_URL",
        "http://prometheus-prometheus-pushgateway.monitoring:9091",
    )
    declared_file = os.environ.get("DECLARED_FILE", "/work/declared.txt")
    tier0_file = os.environ.get("TIER0_FILE", "/inventory/declared_tier0.json")
    exempt_file = os.environ.get("EXEMPT_FILE", "/inventory/exempt.json")

    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    declared, releases = load_declared(declared_file, tier0_file)
    exempt = load_exempt(exempt_file)
    live = collect()
    findings, accounted, refusal = reconcile(live, declared, releases, exempt, now)

    declared_total = len(declared) + len(releases)
    print(f"{declared_total} declarations ({len(declared)} workloads, "
          f"{len(releases)} helm releases) vs {len(live)} live objects")
    if accounted:
        print("accounted for: " + ", ".join(
            f"{k}={v}" for k, v in sorted(accounted.items(), key=lambda kv: -kv[1])))

    if refusal:
        print(f"REFUSING TO REPORT: {refusal}", file=sys.stderr)
    elif findings:
        print(f"{len(findings)} unaccounted object(s):")
        for f in findings:
            print(f"  {f['kind']} {f['namespace']}/{f['name']} — {f['reason']}")
    else:
        print("every running workload and pod is accounted for")

    # A push failure must not read as "nothing wrong" — exit non-zero so the
    # Job fails visibly rather than leaving a stale gauge behind.
    status = push(findings, accounted, refusal, declared_total, len(live), pushgateway)
    if status >= 300:
        print(f"pushgateway returned {status}", file=sys.stderr)
        return 1
    return 1 if refusal else 0


if __name__ == "__main__":
    sys.exit(main())
