# =============================================================================
# Declared-versus-running reconciler  ("do we have stray pods?")
# =============================================================================
# Compares every running workload and pod against what Terraform declares, and
# reports what nothing accounts for. Step 6 of
# docs/plans/2026-09-01-service-identity-and-request-attribution-design.md.
#
# Why nothing else answers this. Kyverno already ENFORCES
# require-trusted-registries, deny-privileged-containers, deny-host-namespaces
# and restrict-sys-admin, so a pod that should never exist cannot be admitted —
# but admission says nothing about whether anyone DECLARED the pod, and an
# object that was admitted correctly two months ago and then dropped out of
# Terraform passes every one of those rules forever. The flow trail
# (goldmane_edges) is no help either: it records what talks, and an undeclared
# workload nobody talks to leaves no edge at all.
#
# THE HARD PART IS "DECLARED", and the answer turned out to be simpler than the
# design assumed. Tier-1 Terraform state lives in the `terraform_state`
# database on the CNPG cluster (root terragrunt.hcl: `backend = "pg"`, one
# schema per stack, table `states`), so a CronJob CAN read it — over an
# ordinary read-only Postgres connection, no CI-generated inventory and no
# ownership-label convention required. Measured 2026-09-01: 162 schemas, 328
# declarations, 1.3s, 8.9 MiB peak psql RSS, because the projection
# (stray_workload_extract.sql) runs server-side and the client only ever sees
# ~330 short rows.
#
# The Tier-0 stacks (infra, platform, cnpg, vault, dbaas, external-secrets) are
# the one gap: their state is local, SOPS-encrypted in the repo, and out of a
# CronJob's reach. Their 11 workloads are committed as declared_tier0.json,
# regenerated by scripts/gen-tier0-workload-inventory.py. Forgetting to
# regenerate produces a visible false positive, never a false negative, and the
# alert text names the script.
#
# WHAT IT FLAGS TODAY — run against live state on 2026-09-01, 339 declarations
# versus 829-840 live objects (the count moves with pod churn between runs), and
# three findings, all of them real:
#
#   Deployment servarr/qbittorrent-exporter   undeclared
#     Live since 2026-03-25, Keel bumped it to v1.7.0 in May, and it appears in
#     no state file, no .tf file and no commit. A Terraform resource deleted
#     from source without a destroy. It even carries this repo's own `tier`
#     label, which is why an ownership-label approach would have missed it.
#   Pod immich/sw-30953                       orphan-pod
#   Pod monitoring/helm-unstick-manual        orphan-pod
#     Both Succeeded, both left behind by hand.
#
# Everything else was accounted for: 311 matched a Terraform declaration by
# name, 50 belong to a declared helm_release, ~460-471 carry an ownerReference
# (pods, so the number moves), 2 are authentik outposts its server builds, 2 are
# kubeadm's coredns and kube-proxy, and 1 is a proxy browser pod started per
# user session.
#
# Not crying wolf is most of the design. See stray_workload_detect.py for the
# per-rule reasoning and stray_workload_detect_test.py for the 32 cases that
# hold it: run `python3 stray_workload_detect_test.py`.
# =============================================================================

locals {
  # Objects that legitimately run with nothing declaring them. One line, one
  # reason, and the list stays short on purpose — every entry here is a place
  # the reconciler is deliberately blind. Prefer a general rule (see the
  # managed_by list below) over adding names.
  stray_workload_exempt = {
    workloads = [
      {
        kind      = "Deployment"
        namespace = "kube-system"
        name      = "coredns"
        # kubeadm creates and upgrades this; the control plane is not managed by
        # Terraform here (kube-apiserver carries no --oidc-* flags either).
        reason = "kubeadm-managed control plane"
      },
      {
        kind      = "DaemonSet"
        namespace = "kube-system"
        name      = "kube-proxy"
        reason    = "kubeadm-managed control plane"
      },
    ]
    # Bare pods (no ownerReference) that a running service creates on demand,
    # matched by label because their names carry a random suffix.
    pod_labels = [
      {
        label = "app"
        value = "proxy-browser"
        # stacks/proxy's broker starts one of these per user, per session. They
        # are declared as behaviour in the broker, not as objects.
        reason = "proxy broker starts these per user session"
      },
    ]
    # `app.kubernetes.io/managed-by` values that name an in-cluster reconciler
    # we run on purpose. Deliberately NOT including "Helm" or "terraform": a
    # Helm-shipped workload is matched to its declared helm_release, and a
    # Terraform-managed one is matched by name, so accepting those labels would
    # only launder objects whose declaration has gone away.
    managed_by = [
      {
        value = "goauthentik.io"
        # The authentik server builds its outpost Deployments itself and sets no
        # ownerReference, so they look bare. It stamps this label on them.
        reason = "authentik server builds its own outpost deployments"
      },
    ]
  }

  # Read-only Postgres login for the Tier-1 state projection.
  stray_workload_db_user = "tf_state_reader"
  stray_workload_db_name = "terraform_state"
}

# A dedicated read-only role rather than reusing `pg-terraform-state`, whose
# credential can WRITE state. That credential would sit in a Secret in this
# namespace, and state-write is arbitrary infrastructure takeover on the next
# apply — a much larger blast radius than the other secrets already here.
#
# Static, deliberately: unlike the Vault-rotated application roles (7-day
# static-creds), this credential grants SELECT on state metadata and nothing
# else, and rotating it would mean a Vault static role in the Tier-0 `vault`
# stack for that one gain. To rotate by hand, taint this resource; the bootstrap
# Job's NAME carries a hash of the password, so a new one is a new Job and the
# role's password is actually reset (see the name below — a Job whose spec is
# unchanged is never re-run, so keying only on the Secret would rotate the
# credential the reader uses without ever telling Postgres about it).
resource "random_password" "stray_workload_db" {
  length  = 32
  special = false
}

resource "kubernetes_secret" "stray_workload_db" {
  metadata {
    name      = "stray-workload-detect-db"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
  data = {
    # Consumed as PGPASSWORD by the extractor's psql.
    READER_PASSWORD = random_password.stray_workload_db.result
    # CNPG superuser, used only by the bootstrap Job below.
    ROOT_PASSWORD = var.dbaas_root_password
  }
}

# Idempotent create of the reader role and its grants, mirroring the db_init Job
# in stacks/goldmane-edge-aggregator.
#
# It runs ONCE, at first apply, and again only when its spec changes (a Job is
# immutable, so Terraform replaces it rather than re-running it). A stack added
# later is therefore NOT covered by a re-run — it is covered by the
# ALTER DEFAULT PRIVILEGES lines in stray_workload_db_init.sql, which grant the
# reader USAGE and SELECT on everything `terraform_state` creates from then on,
# and the pg backend creates each new stack's schema and `states` table as that
# role. If a schema ever does end up ungranted, the extraction fails loudly
# under ON_ERROR_STOP=1 instead of returning a short inventory; the repair is
# `kubectl -n monitoring delete job stray-workload-detect-db-init` and an apply.
resource "kubernetes_job" "stray_workload_db_init" {
  metadata {
    # The name carries a hash of the reader password AND of the bootstrap SQL,
    # which is what makes this Job re-run when either changes. A Job's spec is
    # immutable and an unchanged one is never re-executed, and the password
    # reaches the pod through a secret_key_ref rather than as a value — so
    # without the hash in the name, rotating the credential or adding a grant
    # would change nothing that Terraform can see, and the reader would keep a
    # password Postgres has never been told about.
    name = "stray-workload-detect-db-init-${substr(sha256(
      "${random_password.stray_workload_db.result}${file("${path.module}/stray_workload_db_init.sql")}"
    ), 0, 8)}"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
  spec {
    backoff_limit = 3
    template {
      metadata {}
      spec {
        restart_policy = "Never"
        container {
          name  = "db-init"
          image = "docker.io/library/postgres:16-alpine"
          # The SQL lives in its own file (stray_workload_db_init.sql) rather
          # than a heredoc, so nothing needs Terraform template escaping and the
          # whole script is runnable by hand. psql interpolates the password as
          # a quoted literal; it never appears in the Job spec.
          command = ["sh", "-c",
            "psql -v ON_ERROR_STOP=1 -v reader_password=\"$READER_PASSWORD\" -f /sql/stray_workload_db_init.sql && echo 'reader role ready'"
          ]
          env {
            name  = "PGHOST"
            value = var.postgresql_host
          }
          env {
            name  = "PGUSER"
            value = "root"
          }
          env {
            # psql defaults the database name to the username and the root user
            # has no root-named database. Everything in the script is cluster-
            # or current-database-scoped, so terraform_state is the right place
            # to run all of it from.
            name  = "PGDATABASE"
            value = local.stray_workload_db_name
          }
          env {
            name = "PGPASSWORD"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.stray_workload_db.metadata[0].name
                key  = "ROOT_PASSWORD"
              }
            }
          }
          env {
            name = "READER_PASSWORD"
            value_from {
              secret_key_ref {
                name = kubernetes_secret.stray_workload_db.metadata[0].name
                key  = "READER_PASSWORD"
              }
            }
          }
          volume_mount {
            name       = "sql"
            mount_path = "/sql"
            read_only  = true
          }
          resources {
            requests = {
              cpu    = "10m"
              memory = "32Mi"
            }
            limits = {
              memory = "64Mi"
            }
          }
        }
        volume {
          name = "sql"
          config_map {
            name = kubernetes_config_map.stray_workload_detect_script.metadata[0].name
          }
        }
      }
    }
  }
  # Waiting is a deliberate coupling, stated so it is not a surprise: an apply of
  # this stack while CNPG is unreachable fails here, in 2 minutes, with an error
  # naming this Job. The alternative (fire and forget) hides a failed bootstrap
  # until StrayWorkloadDetectorStale notices ~26h later, and finding out at apply
  # time is worth more than that. A healthy run takes about 2 seconds — 325
  # grants in one psql session, measured 2026-09-01. Same shape as the db_init
  # Job in stacks/goldmane-edge-aggregator.
  wait_for_completion = true
  timeouts {
    create = "2m"
  }
  lifecycle {
    # KYVERNO_LIFECYCLE_V1: Kyverno injects dns_config (ndots=2); ignore it so
    # this idempotent Job isn't replaced (Jobs are immutable) on every apply.
    ignore_changes = [spec[0].template[0].spec[0].dns_config]
  }
}

resource "kubernetes_service_account" "stray_workload_detect" {
  metadata {
    name      = "stray-workload-detect"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
}

# Read-only, cluster-wide, metadata only in practice: an undeclared workload can
# be in any namespace, and the job never needs a write verb or a pod spec.
resource "kubernetes_cluster_role" "stray_workload_detect" {
  metadata {
    name = "stray-workload-detect"
  }
  rule {
    api_groups = ["apps"]
    resources  = ["deployments", "statefulsets", "daemonsets"]
    verbs      = ["get", "list"]
  }
  rule {
    api_groups = ["batch"]
    resources  = ["cronjobs"]
    verbs      = ["get", "list"]
  }
  rule {
    api_groups = [""]
    resources  = ["pods"]
    verbs      = ["get", "list"]
  }
}

resource "kubernetes_cluster_role_binding" "stray_workload_detect" {
  metadata {
    name = "stray-workload-detect"
  }
  role_ref {
    api_group = "rbac.authorization.k8s.io"
    kind      = "ClusterRole"
    name      = kubernetes_cluster_role.stray_workload_detect.metadata[0].name
  }
  subject {
    kind      = "ServiceAccount"
    name      = kubernetes_service_account.stray_workload_detect.metadata[0].name
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
}

resource "kubernetes_config_map" "stray_workload_detect_script" {
  metadata {
    name      = "stray-workload-detect-script"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
  data = {
    "stray_workload_detect.py"   = file("${path.module}/stray_workload_detect.py")
    "stray_workload_extract.sql" = file("${path.module}/stray_workload_extract.sql")
    "stray_workload_db_init.sql" = file("${path.module}/stray_workload_db_init.sql")
  }
}

resource "kubernetes_config_map" "stray_workload_detect_inventory" {
  metadata {
    name      = "stray-workload-detect-inventory"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
  }
  data = {
    # Regenerated by scripts/gen-tier0-workload-inventory.py — see the header
    # comment above for why this half cannot be read at runtime.
    "declared_tier0.json" = file("${path.module}/declared_tier0.json")
    "exempt.json"         = jsonencode(local.stray_workload_exempt)
  }
}

resource "kubernetes_cron_job_v1" "stray_workload_detect" {
  metadata {
    name      = "stray-workload-detect"
    namespace = kubernetes_namespace.monitoring.metadata[0].name
    labels = {
      app  = "stray-workload-detect"
      tier = var.tier
    }
  }
  spec {
    concurrency_policy            = "Forbid"
    failed_jobs_history_limit     = 3
    successful_jobs_history_limit = 3
    # 07:05, daily. Declarations change at CI-apply pace, not by the minute, so
    # a daily pass is the right resolution. The time is chosen to sit clear of
    # the backup chain (02:00-06:00) and the nightly drift plan (04:00), and to
    # land a new finding on the alert board before the 08:00 alert digest reads
    # it — StrayWorkloadDetected has for: 30m, so a 07:05 push fires ~07:35.
    schedule                  = "5 7 * * *"
    starting_deadline_seconds = 600
    job_template {
      metadata {}
      spec {
        backoff_limit              = 2
        ttl_seconds_after_finished = 86400
        template {
          metadata {
            labels = {
              app = "stray-workload-detect"
            }
          }
          spec {
            restart_policy       = "OnFailure"
            service_account_name = kubernetes_service_account.stray_workload_detect.metadata[0].name

            # Two containers because the two halves want different tools: psql
            # for the state projection, stdlib python for the reconciliation.
            # Adding a Postgres driver to the python image would mean a runtime
            # pip install, which is the status-page-pusher anti-pattern
            # (.claude/CLAUDE.md); shipping the query to psql keeps both halves
            # on stock images with nothing installed at runtime.
            init_container {
              name              = "extract-declared"
              image             = "docker.io/library/postgres:16-alpine"
              image_pull_policy = "IfNotPresent"
              # ON_ERROR_STOP=1 is the load-bearing flag: without it a schema
              # the reader cannot SELECT is skipped with a warning and the
              # inventory comes back SHORT, which reads as a cluster full of
              # stray workloads. With it, the init container fails, the Job
              # fails, and StrayWorkloadDetectorStale fires.
              command = ["sh", "-c",
                "psql -v ON_ERROR_STOP=1 -At -F'|' -q -f /scripts/stray_workload_extract.sql > /work/declared.txt && wc -l /work/declared.txt"
              ]
              env {
                name  = "PGHOST"
                value = var.postgresql_host
              }
              env {
                name  = "PGUSER"
                value = local.stray_workload_db_user
              }
              env {
                name  = "PGDATABASE"
                value = local.stray_workload_db_name
              }
              env {
                # Self-imposed belt to the read-only role's braces: even a
                # future edit to the SQL cannot write through this session.
                name  = "PGOPTIONS"
                value = "-c default_transaction_read_only=on"
              }
              env {
                name = "PGPASSWORD"
                value_from {
                  secret_key_ref {
                    name = kubernetes_secret.stray_workload_db.metadata[0].name
                    key  = "READER_PASSWORD"
                  }
                }
              }
              volume_mount {
                name       = "script"
                mount_path = "/scripts"
                read_only  = true
              }
              volume_mount {
                name       = "work"
                mount_path = "/work"
              }
              resources {
                requests = {
                  cpu    = "10m"
                  memory = "16Mi"
                }
                limits = {
                  # MEASURED, not guessed (2026-09-01): psql's peak VmHWM for
                  # the full 162-schema extraction is 8.9 MiB, because the
                  # jsonb work happens server-side and the client only buffers
                  # the ~330-row projection. 64Mi is ~7x that. Under-sizing a
                  # detector's container is not cosmetic here — helm-unstick
                  # was memcg-OOM-killed on every run at 96Mi and its `|| true`
                  # turned that into a silent empty result, so it reported
                  # success while inspecting nothing.
                  memory = "64Mi"
                }
              }
            }

            container {
              name              = "reconcile"
              image             = "docker.io/library/python:3.12-alpine"
              image_pull_policy = "IfNotPresent"
              command           = ["python3", "/scripts/stray_workload_detect.py"]
              volume_mount {
                name       = "script"
                mount_path = "/scripts"
                read_only  = true
              }
              volume_mount {
                name       = "inventory"
                mount_path = "/inventory"
                read_only  = true
              }
              volume_mount {
                name       = "work"
                mount_path = "/work"
                read_only  = true
              }
              resources {
                requests = {
                  cpu    = "10m"
                  memory = "48Mi"
                }
                limits = {
                  # MEASURED, not guessed (2026-09-01): 840 live objects
                  # arrive as 3.61 MiB because the apiserver is asked for
                  # PartialObjectMetadataList and drops every pod spec (the
                  # same listing with specs is 7.7 MiB for pods alone), and
                  # peak RSS is 37.2 MiB of which 20 MiB is the interpreter.
                  # 128Mi is ~3.4x. Re-measure rather than assume if the pod
                  # count grows a lot.
                  memory = "128Mi"
                }
              }
            }

            volume {
              name = "script"
              config_map {
                name = kubernetes_config_map.stray_workload_detect_script.metadata[0].name
              }
            }
            volume {
              name = "inventory"
              config_map {
                name = kubernetes_config_map.stray_workload_detect_inventory.metadata[0].name
              }
            }
            volume {
              name = "work"
              empty_dir {}
            }
            dns_config {
              option {
                name  = "ndots"
                value = "2"
              }
            }
          }
        }
      }
    }
  }
  depends_on = [kubernetes_job.stray_workload_db_init]
  lifecycle {
    # KYVERNO_LIFECYCLE_V1: Kyverno admission webhook mutates dns_config with ndots=2
    ignore_changes = [spec[0].job_template[0].spec[0].template[0].spec[0].dns_config]
  }
}
