{
 "title": "iDRAC - Host Stats",
 "description": "SNMP Based Dashboard to Monitor Dell Hosts via iDRAC - by ilovepancakes95",
 "tags": [
  "idrac",
  "telegraf",
  "snmp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "iDRAC Summary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Service Tag",
   "type": "text",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "options": { "content": "GCFSDN2" },
   "targets": [
    {
     "measurement": "idrac-hosts",
     "query": "SELECT \"system-servicetag\" FROM /^$idrac_host$/ WHERE (\"system-name\" =~ /^$idrac_host$/) AND $timeFilter",
     "select": [
      [
       { "params": [ "system-servicetag" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Threads",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "r730_idrac_redfish_system_processor_total_threads",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "memory-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(r730_idrac_redfish_system_memory_capacity)",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "temp-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Storage",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(r730_idrac_redfish_system_storage_volume_capacity)",
     "measurement": "idrac-hosts",
     "query": "SELECT \"power-state\" FROM \"esxi-01-idrac\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "storage-status" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Watts",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "alias": "System Watts",
     "expr": "r730_idrac_redfish_chassis_power_average_consumed_watts",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "CPU 1 Temp",
     "expr": "r730_idrac_redfish_chassis_temperature_celsius{sensor=\"CPU1 Temp\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "cpu1-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Air Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Inlet Temp",
     "expr": "r730_idrac_redfish_chassis_temperature_celsius{sensor=\"System Board Inlet Temp\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "System Watts",
     "expr": "r730_idrac_redfish_chassis_power_voltage_volts{power_voltage=~\"PS2 Voltage.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "System Board Exhaust Temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "alias": "Inlet Temp",
     "expr": "r730_idrac_redfish_chassis_temperature_celsius{sensor=\"System Board Exhaust Temp\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "inlet-temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 10" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Input Voltage (UPS power supply)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "System Watts",
     "expr": "r730_idrac_redfish_chassis_power_voltage_volts{power_voltage=~\"PS1 Voltage.*\"}",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "system-watts" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  },
  {
   "title": "Average Fan Speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Fan 1",
     "expr": "avg(r730_idrac_redfish_chassis_fan_rpm)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan1-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan2-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 3",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan3-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 4",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan4-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 5",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan5-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    },
    {
     "alias": "Fan 6",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "idrac-hosts",
     "select": [
      [
       { "params": [ "fan6-speed" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "system-name", "operator": "=~", "value": "/^$idrac_host$/" }
     ]
    }
   ]
  }
 ]
}