{
 "title": "NVIDIA DCGM Exporter Dashboard",
 "description": "This dashboard is to display the metrics from DCGM Exporter on a Kubernetes (1.13+) cluster",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "GPU Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_GPU_TEMP",
     "legendFormat": "GPU 0"
    }
   ]
  },
  {
   "title": "GPU Current Temp",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_GPU_TEMP"
    }
   ]
  },
  {
   "title": "GPU Power Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_POWER_USAGE",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Power Total",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(nvidia_tesla_t4_DCGM_FI_DEV_POWER_USAGE)"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_GPU_UTIL",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Framebuffer Mem Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_FB_USED",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  },
  {
   "title": "GPU SM Clocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "nvidia_tesla_t4_DCGM_FI_DEV_SM_CLOCK* 1000000",
     "legendFormat": "GPU {{gpu}}"
    }
   ]
  }
 ]
}