{
 "title": "Huawei UPS 2000",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Huawei UPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "System uptime",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_sysUpTime / 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Remaining",
   "type": "gauge",
   "description": "Battery Charge Remaining Expressed as a Percent of Full Charge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_upsEstimatedChargeRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Until Battery Depletion",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ups_upsEstimatedMinutesRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds On Battery",
   "type": "gauge",
   "description": "If the unit is on battery power, the elapsed time since the UPS last switched to battery power, or the time since the network management subsystem was last restarted, whichever is less - 1.3.6.1.2.1.33.1.2.2",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsSecondsOnBattery", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active Alarms",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsAlarmsPresent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Percent Load",
   "type": "stat",
   "description": "The percentage of the UPS power capacity presently being used on this output line, i.e., the greater of the percent load of true power capacity and the percent load of VA. - 1.3.6.1.2.1.33.1.4.4.1.5",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsOutputPercentLoad", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsInputVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ups_upsBatteryVoltage / 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_upsInputVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "ups_upsOutputVoltage", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ambient temperature at or near the UPS Battery",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "ups_upsBatteryTemperature / 100000000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    { "expr": "ups_upsOutputCurrent / 10", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Active power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kwatt" } },
   "targets": [
    {
     "expr": "ups_hwUpsOutputActivePowerA / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Apparent power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "kvoltamp" } },
   "targets": [
    {
     "expr": "ups_hwUpsOutputAppearancePowerA / 10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Battery Remaining",
   "type": "timeseries",
   "description": "Battery Charge Remaining Expressed as a Percent of Full Charge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "ups_upsEstimatedChargeRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time Until Battery Depletion",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "expr": "ups_upsEstimatedMinutesRemaining",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Automatic Transfer Switch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Current Power Source",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "automatic_transfer_switch_power_mode",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "automatic_transfer_switch_load_power_watts / 10 * automatic_transfer_switch_power_mode",
     "legendFormat": "Inverter"
    },
    {
     "expr": "automatic_transfer_switch_load_power_watts / 10 * (1-automatic_transfer_switch_power_mode)",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Daily Total Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "increase(automatic_transfer_switch_totalele_add[1d]) * 10",
     "legendFormat": "Inverter"
    },
    {
     "expr": "increase(automatic_transfer_switch_dwele_add[1d]) * 10",
     "legendFormat": "Grid"
    }
   ]
  },
  {
   "title": "Total Power by Source",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 21, "x": 3, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "watth" } },
   "targets": [
    {
     "expr": "automatic_transfer_switch_dwele_add * 10",
     "legendFormat": "Grid Power"
    },
    {
     "expr": "automatic_transfer_switch_totalele_add * 10",
     "legendFormat": "Inverter Power"
    }
   ]
  }
 ]
}