# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
variable "kube_config_path" {
  type    = string
  default = "~/.kube/config"
  sensitive = true
}

provider "kubernetes" {
  config_path = var.kube_config_path
}

provider "helm" {
  kubernetes = {
    config_path = var.kube_config_path
  }
}
