{
 "title": "IDRAC",
 "tags": [
  "dell",
  "idrac",
  "lenovo",
  "redfish"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": "label_values(r730_idrac_idrac_system_machine_info,job)"
   },
   {
    "name": "instance",
    "query": "label_values(r730_idrac_idrac_system_machine_info{job=~\"$job\"},instance)"
   }
  ]
 },
 "panels": [
  { "title": "Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_globalSystemStatus{instance=~\"$instance\", job=~\"$job\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "BIOS version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_idrac_system_bios_info{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{version}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "r730_idrac_idrac_memory_module_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_memory_module_health{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_memory_module_capacity_bytes{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_memory_module_speed_mhz{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Vendor",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_idrac_system_machine_info{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{manufacturer}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Memory Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "sum(r730_idrac_memoryDeviceSize{instance=\"$instance\", job=~\"$job\"}) * 1024",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "SKU",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "CPUs",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(r730_idrac_processorDeviceStatus{instance=\"$instance\", job=~\"$job\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "count(r730_idrac_idrac_storage_drive_info{instance=\"$instance\", job=~\"$job\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Indicator LED",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_idrac_system_indicator_led_on{instance=\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{state}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_systemPowerState{instance=\"$instance\", job=~\"$job\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Disk Drives",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "expr": "r730_idrac_idrac_storage_drive_info{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_storage_drive_health{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_storage_drive_capacity_bytes{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "expr": "r730_idrac_idrac_network_port_health{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_network_port_link_up{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_network_port_current_speed_mbps{job=~\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "r730_idrac_idrac_network_adapter_health{job=~\"$job\", instance=~\"$instance\"}"
    }
   ]
  },
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(r730_idrac_temperatureProbeReading{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval]) / 10",
     "legendFormat": "{{temperatureProbeLocationName}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fans",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "rotrpm" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(r730_idrac_coolingDeviceReading{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{coolingDeviceLocationName}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Power", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "Power Supplies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(r730_idrac_powerSupplyOutputWatts{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Output {{powerSupplyLocationName}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    },
    {
     "expr": "avg_over_time(r730_idrac_idrac_power_supply_input_watts{instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "Input PSU-{{id}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg(r730_idrac_powerSupplyCurrentInputVoltage{instance=~\"$instance\", job=~\"$job\"})",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Power Consumption",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "avg_over_time(r730_idrac_amperageProbeReading{amperageProbeLocationName=\"System Board Pwr Consumption\",instance=~\"$instance\",job=~\"$job\"}[$__rate_interval])",
     "legendFormat": "{{amperageProbeLocationName}}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "expr": "r730_idrac_idrac_power_control_capacity_watts{id=\"0\",instance=~\"$instance\", job=~\"$job\"}",
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  { "title": "Event log", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "System Event Log (SEL)",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "last_over_time(r730_idrac_idrac_events_log_entry{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval) * 1000 < ${__to}\nand \nlast_over_time(r730_idrac_idrac_events_log_entry{job=~\"$job\", instance=~\"$instance\"}[$__interval] offset -$__interval) * 1000 > ${__from}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}