when:
  event: push

clone:
  git:
    image: alpine
    commands:
      - "apk update && apk add git"
      - "for i in 1 2 3 4 5; do git clone https://github.com/ViktorBarzin/infra.git . && break || echo \"Clone attempt $i failed, retrying in 10s...\" && sleep 10; done"
      - "git checkout $CI_COMMIT_SHA"

steps:
  - name: build-image
    image: woodpeckerci/plugin-docker-buildx
    settings:
      username: "viktorbarzin"
      password:
        from_secret: dockerhub-pat
      repo: viktorbarzin/infra
      dockerfile: cli/Dockerfile
      context: cli
      auto_tag: true
