# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "pg" {
    conn_str    = "postgres://terraform_state:CqqXJIkGJy9deH5p-kv4@10.0.20.200:5432/terraform_state?sslmode=disable"
    schema_name = "f1-stream"
  }
}
