# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "pg" {
    conn_str    = "postgres://terraform_state:SBlzGxotNUN6HH9d0S-m@10.0.20.200:5432/terraform_state?sslmode=disable"
    schema_name = "f1-stream"
  }
}
